### ISSUE TITLE
mt_align_start_end() introduces NaNs and -Infs

### ISSUE THREAD

**Issue by mstbr** [PascalKieslich/mousetrap#10] opened 2019-09-03 18:42 UTC
Hey Pascal,

mt_align_start_end() has been giving me some headaches similar to the ones in this forum thread:
https://forum.cogsci.nl/discussion/4415/question-about-mt-time-normalize-function-in-mousetrap-r-package?

My first intuition was to blame exceedingly short trajectories, too, and excluding them worked until it didn't. Following your second suggestion, I took care of the 'no-variation' trajectories, and that also seemed to work for a while/in some cases.

I believe neither the first nor the second of the conditions you identified as problematic holds true for this small set of values:

> mt_data$trajectories[,,]
  timestamps xpos ypos
[1,] 0 -20 30
[2,] 10 30 40
[3,] 20 -10 50
[4,] 30 40 60
[5,] 40 -20 80

However, calling mt_align_start_end() with argument defaults on these values results in the following:

> mtdata$se_trajectories[,,]
  timestamps xpos ypos
[1,] 0 NaN 0.0
[2,] 10 -Inf 0.2
[3,] 20 -Inf 0.4
[4,] 30 -Inf 0.6
[5,] 40 NaN 1.0

Sorry if this is not the conventional way of filing an "issue", this is my first time doing anything like this on GitHub or anywhere.

**Comment by PascalKieslich** [comment] 2019-09-03 19:06
Hi there,

that's an interesting example. I believe the cause of the problem is that your trajectory has the same x coordinate at the start and end point. In this case , it is unclear how the rescaling/realignment on the x dimension should work, so I believe that NAs are actually the "desired" behavior here (although a proper error message might be nice, will see whether I can implement one).

This means that the solution would have to happen in the preprocessing, either by excluding all trajectories where the x start and end coordinate is identical and/or where the y start and end coordinate is identical. Alternatively, you could introduce some variation to the respective end coordinate but this would create a somewhat artifical trajectory that would be considerably stretched along the corresponding dimension.

Hope this helps! Please let me know if you have another suggestion what should be happening in these cases.

Best,

Pascal

PS: This is definitely a case for filing an issue. Usually you would try to create a code with a reproducable example that I could run, but it is also fine to first just raise the issue and then I'll let you know if I need more context.

**Comment by mstbr** [comment] 2019-09-04 14:17
Hey,

yes, the problem generally seems to be identical first and last values, good catch and thank you! And of course I have to agree that those NAs make total sense there.

It appears there are several ways in which mt_align_start_end() can lead to missing values:

1. The first and last values along a dimension are identical--like in my case and, as I've now seen,  [here](http://forum.cogsci.nl/discussion/5094/conceptual-q-mt-align-start-end)
2. There is no variation within a trial
3. There are <=2 logged positions

On the one hand, it seems unclear exactly how frequent these conditions actually come to exist in practice, but on the other: If they do, users of your package will probably end up with an error only upon performing subsequent steps, i.e. probably during time-normalization, which is definitely not the most straightforward thing to figure out when you're "just a user". So I'd also argue for a warning message when mt_align_start_end() comes up with missing values, not leaving users in the dark, but also not changing the "desired" behavior of the function. Just my 2 cents, though.

I suppose this issue can now be closed, and I'd be happy to do so--should I?

Cheers!

**Comment by PascalKieslich** [comment] 2019-09-04 14:41
Hi!
Thanks for the summary and great that we both agree on the way forward (implementing a warning message). I'd suggest that we leave the issue open as a reminder for me to implement the warning messages. Once I have done this, I will close the issue.
Best,
Pascal

**Closed** 2019-10-04 14:15 UTC
